apiVersion: v1
kind: Namespace
metadata:
  name: {{ required "targetNamespace is required" .Values.targetNamespace }}
  {{- if .Values.privileged }}
  labels:
    pod-security.kubernetes.io/enforce: privileged
  {{- end }}
