apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-git-server.fullname" . }}-seed
  labels:
    {{- include "test-git-server.labels" . | nindent 4 }}
data:
  {{- range .Values.seedRepos }}
  {{- if not .noConfig }}
  {{ .name }}.json: {{ .devcontainerJson | quote }}
  {{- end }}
  {{- if .dockerfile }}
  {{ .name }}.Dockerfile: {{ .dockerfile | quote }}
  {{- end }}
  {{- end }}
