apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devcontainer-builder.fullname" . }}-registry-mapping
  labels:
    {{- include "devcontainer-builder.labels" . | nindent 4 }}
data:
  registry-mapping.json: {{ .Values.registryMapping.rules | toJson | quote }}
