{{- if not .Values.registryAuth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devcontainer-builder.secretName" . }}
  labels:
    {{- include "devcontainer-builder.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "devcontainer-builder.dockerConfigJson" . | b64enc }}
{{- end }}
