apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-openssh-server.fullname" . }}
  labels:
    {{- include "test-openssh-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "test-openssh-server.labels" . | nindent 4 }}
  ports:
    - name: ssh
      port: {{ .Values.service.port }}
      targetPort: ssh
